rvm:
 - 2.3.3
before_install:
 - sed -i '2d' Gemfile
 - sudo apt-get update -qq
 - sudo apt-get install -qq postgresql-server-dev-9.6
before_script:
 - psql -c 'create database the_x_effect_test;' -U postgres
script:
 - bundle exec bin/rake db:create
 - bundle exec bin/rake db:migrate
 - bundle exec rspec spec
