rvm:
- 2.3.3

before_install:
- sed -i '2d' Gemfile
- sudo apt-get update -qq
- sudo apt-get install -qq postgresql-server-dev-9.6

before_script:
 - psql -c 'create database the-x-effect_test;' -U postgres

script: bundle exec rspec spec
